#!/bin/sh
# Took me a day to realize that nicify.pl will screw over if you don't explicitly run nicify.pl as root
# Lesson learned...
cd NICTemplate/SettingsKit.nic/
su root -c "$THEOS/bin/nicify.pl ./"
mv -f ./iphone_SettingsKit_preference_bundle.nic.tar $THEOS/templates/SettingsKit.nic.tar